

GET http://localhost:5088/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJjZjQ0ZDU5MC0wMDMxLTQ0OWQtYmRhNC0xMDc3ZmM3YzZlYzkiLCJlbWFpbCI6ImJyYXlhbkBleGFtcGxlLmNvbSIsInVuaXF1ZV9uYW1lIjoiYnJheWFuQGV4YW1wbGUuY29tIiwicm9sZSI6IlVzZXIiLCJqdGkiOiIzOTY1NDgyNy1iN2Q5LTQ0YTktOGZhZC00YzQzZTkyYmU5NTQiLCJuYmYiOjE3ODQ4NTk2MDksImV4cCI6MTc4NDg2NjgwOSwiaWF0IjoxNzg0ODU5NjA5LCJpc3MiOiJTYWZlVmF1bHRBcGkiLCJhdWQiOiJTYWZlVmF1bHRVc2VycyJ9.hEOr2TrRlNvO5U2oiYF4QekL6dWqRQgdRVMNUuwBmlI

###

GET http://localhost:5088/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI4ZjA0YWVkZC05ZDNmLTQ2NTQtOWMzNi1kYmZkMzc3ODgzYmUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwidW5pcXVlX25hbWUiOiJhZG1pbkBleGFtcGxlLmNvbSIsInJvbGUiOiJBZG1pbiIsImp0aSI6ImU5NjdmNmVhLWEwY2QtNGM2ZC04NDg2LTdiZDNmMDM0YjIwMSIsIm5iZiI6MTc4NDg1OTY0OCwiZXhwIjoxNzg0ODY2ODQ4LCJpYXQiOjE3ODQ4NTk2NDgsImlzcyI6IlNhZmVWYXVsdEFwaSIsImF1ZCI6IlNhZmVWYXVsdFVzZXJzIn0.QxG9xocVEioFu7yvfIhylIY55v4_m2SbhiuH7W2nL-w

###

POST http://localhost:5088/api/financialrecords
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJjZjQ0ZDU5MC0wMDMxLTQ0OWQtYmRhNC0xMDc3ZmM3YzZlYzkiLCJlbWFpbCI6ImJyYXlhbkBleGFtcGxlLmNvbSIsInVuaXF1ZV9uYW1lIjoiYnJheWFuQGV4YW1wbGUuY29tIiwicm9sZSI6IlVzZXIiLCJqdGkiOiIzOTY1NDgyNy1iN2Q5LTQ0YTktOGZhZC00YzQzZTkyYmU5NTQiLCJuYmYiOjE3ODQ4NTk2MDksImV4cCI6MTc4NDg2NjgwOSwiaWF0IjoxNzg0ODU5NjA5LCJpc3MiOiJTYWZlVmF1bHRBcGkiLCJhdWQiOiJTYWZlVmF1bHRVc2VycyJ9.hEOr2TrRlNvO5U2oiYF4QekL6dWqRQgdRVMNUuwBmlI
Content-Type: application/json

{   
    "accountName": "Primary Checking",
}
###